cursor_arrow = ( "xX                      ",
                 "X.X                     ",
                 "X..X                    ",
                 "X...X                   ",
                 "X....X                  ",
                 "X.....X                 ",
                 "X......X                ",
                 "X.......X               ",
                 "X........X              ",
                 "X.........X             ",
                 "X......XXXXX            ",
                 "X...X..X                ",
                 "X..XX..X                ",
                 "X.X XX..X               ",
                 "XX   X..X               ",
                 "X     X..X              ",
                 "      X..X              ",
                 "       X..X             ",
                 "       X..X             ",
                 "        XX              ",
                 "                        ",
                 "                        ",
                 "                        ",
                 "                        ")

cursor_no = ("                        ",
         "                        ",
         "         XXXXXX         ",
         "       XX......XX       ",
         "      X..........X      ",
         "     X....XXXX....X     ",
         "    X...XX    XX...X    ",
         "   X.....X      X...X   ",
         "   X..X...X      X..X   ",
         "  X...XX...X     X...X  ",
         "  X..X  X...X     X..X  ",
         "  X..X   X...X    X..X  ",
         "  X..X    X.,.X   X..X  ",
         "  X..X     X...X  X..X  ",
         "  X...X     X...XX...X  ",
         "   X..X      X...X..X   ",
         "   X...X      X.....X   ",
         "    X...XX     X...X    ",
         "     X....XXXXX...X     ",
         "      X..........X      ",
         "       XX......XX       ",
         "         XXXXXX         ",
         "                        ",
         "                        ",
        )